[project]
name = "hexa-swapi-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "domain",
    "pytest>=8.3.4",
    "ruff>=0.9.1"
]

[tool.uv.workspace]
members = ["domain"]

[tool.uv.sources]
domain = { workspace = true }

[tool.hatch.build.targets.wheel]
packages = ["src/hexa_swapi_python"]

[project.scripts]
main = "hexa_swapi_python.main:main"
