### Test like in integration test
POST http://localhost:8080/rescueFleets
Content-Type: application/json

{
  "number_of_passenger": 12
}

### Real test
POST http://localhost:8080/rescueFleets
Content-Type: application/json

{
  "number_of_passenger": 1220
}
